services:
  app:
    container_name: carnet-app
    image: ghcr.io/samwin25/carnet-de-recettes-laravel:latest
    restart: unless-stopped
    env_file: .env
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000" # ✅ Tu exposes bien ton application Laravel
    depends_on:
      - db
    networks:
      - carnet-network

  db:
    image: postgres:14
    container_name: carnet-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: recettes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: samwin25
    volumes:
      - carnet-db-data:/var/lib/postgresql/data
    networks:
      - carnet-network

  web:
    image: nginx:stable-alpine
    container_name: carnet-nginx
    restart: unless-stopped
    ports:
      - "9010:80" # seul point d'accès exposé
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./carnet-de-recettes-laravel:/var/www/html
    depends_on:
      - app
    networks:
      - carnet-network

volumes:
  carnet-db-data:

networks:
  carnet-network:
