# Copier le contenu du nginx.conf racine dans docker/nginx/nginx.conf pour que le service Nginx utilise la bonne configuration
# Ce fichier est requis pour que le service Nginx démarre correctement

events {}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile        on;
  keepalive_timeout  65;

  include /etc/nginx/conf.d/*.conf;
}
